home/urls.py
from django.urls import path
# from .views import main_page
from .views import MainPageView

app_name = 'home'

urlpatterns = [
    # path('', main_page, name='main_page'),
    path('', MainPageView.as_view(), name='main_page'),
]

yummy_jan/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from yummy_jan import settings

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.core.validators import RegexValidator
from ckeditor.fields import RichTextField


class DishCategory(models.Model):
    name = models.CharField(max_length=255, unique=True)
    position = models.PositiveSmallIntegerField()
    is_visible = models.BooleanField(default=True)

    class Meta:
        verbose_name_plural = 'Dish Categories'
        ordering = ('position',)

    def __iter__(self):
        dishes = self.dishes.filter(is_visible=True)
        for dish in dishes:
            yield dish

    def __str__(self):
        return f'{self.name}'


class Dish(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)
    ingredients = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    photo = models.ImageField(upload_to='dishes/', blank=True)
    is_visible = models.BooleanField(default=True)
    position = models.PositiveSmallIntegerField()

    category = models.ForeignKey(DishCategory, on_delete=models.PROTECT, related_name='dishes')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name_plural = 'Dishes'
        ordering = ('position',)
        constraints = [
            models.UniqueConstraint(fields=['position', 'category'], name='unique_position_per_each_category'),
        ]
        unique_together = ['id', 'slug']


class FooterItem(models.Model):
    address = RichTextField()
    phone = models.CharField(max_length=255)
    email = models.EmailField()
    working_hours = RichTextField()
    twitter = models.URLField(max_length=255, blank=True)
    facebook = models.URLField(max_length=255, blank=True)
    instagram = models.URLField(max_length=255, blank=True)
    youtube = models.URLField(max_length=255, blank=True)

class Chef(models.Model):
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    appointment = models.CharField(max_length=50)
    description = models.TextField(max_length=1000, blank=True)
    position = models.PositiveSmallIntegerField(unique=True)
    is_visible = models.BooleanField(default=True)
    photo = models.ImageField(upload_to='chefs_photos', blank=True)

    def __str__(self):
        return f'{self.name} {self.surname}'

class Events(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    description = models.TextField()
    photo = models.ImageField(upload_to='events')
    is_visible = models.BooleanField(default=True)
    position = models.PositiveSmallIntegerField(default=1)

class Gallery(models.Model):
    photo = models.ImageField(upload_to='gallery')
    is_visible = models.BooleanField(default=True)
    position = models.PositiveSmallIntegerField(default=1)
    name = models.CharField(max_length=50)


class Reservation(models.Model):
    name = models.CharField(max_length=255)

    phone_regex = RegexValidator(
        regex=r'^\+?380\d{9}$',
        message="Phone number must be format '+380xxxxxxxxx'. Up to 15 digits"
    )
    phone = models.CharField(max_length=255, validators=[phone_regex])
    email = models.EmailField()
    date = models.DateField()
    time = models.TimeField()
    message = models.TextField(blank=True)
    number_people = models.PositiveSmallIntegerField()

    is_conformed = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_at',)

home/forms.py
from django import forms
from .models import Reservation

class ReservationForm(forms.ModelForm):

    def clean_name(self):
        name = self.cleaned_data['name']
        return f'*{name}*'

    class Meta:
        # к какой модели привязиваюсь
        model = Reservation
        # які поля будуть вноситись через форму
        fields = ('name', 'email', 'phone', 'date', 'time', 'message', 'number_people')

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'id': 'name', 'placeholder': 'Your name 2', 'data-rule': 'minlen:4', 'data-msg': 'Please enter at least 4 chars'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'id': 'email', 'placeholder': 'Your Email', 'data-rule': 'email', 'data-msg': 'Please enter a valid email'}),
            'phone': forms.TextInput(attrs={'class': 'form-control', 'id': 'phone', 'placeholder': 'Your Phone', 'data-rule': 'minlen:4', 'data-msg': 'Please enter at least 4 chars'}),
            'date': forms.DateInput(attrs={'class': 'form-control', 'id': 'date', 'placeholder': 'Date', 'data-rule': 'minlen:4', 'data-msg': 'Please enter at least 4 chars'}),
            'time': forms.TimeInput(attrs={'class': 'form-control', 'id': 'time', 'placeholder': 'Time', 'data-rule': 'minlen:4', 'data-msg': 'Please enter at least 4 chars'}),
            'number_people': forms.NumberInput(attrs={'class': 'form-control', 'id': 'people', 'placeholder': '# of people', 'data-rule': 'minlen:1', 'data-msg': 'Please enter at least 1 chars'}),
            'message': forms.Textarea(attrs={'class': 'form-control', 'rows': '5', 'placeholder': 'Message'})
        }

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from .models import DishCategory, Chef, Events, Gallery
from .forms import ReservationForm

class MainPageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        reservation_form = ReservationForm()

        context['categories'] = DishCategory.objects.filter(is_visible=True)
        context['chefs'] = Chef.objects.filter(is_visible=True)
        context['events'] = Events.objects.filter(is_visible=True)
        context['gallery'] = Gallery.objects.filter(is_visible=True)
        context['reservation_form'] = reservation_form

        return context

    def post(self, request, *args, **kwargs):
        reservation_form = ReservationForm(request.POST)
        print('Test')
        if reservation_form.is_valid():
            print('Good')
            reservation_form.save()
            return render(request, 'index.html', {'reservation_form': reservation_form})
        else:
            print('Bad')
            return render(request, 'index.html', {'reservation_form': reservation_form})


# def main_page(request):
#     categories = DishCategory.objects.filter(is_visible=True)
#     chefs = Chef.objects.filter(is_visible=True)
#     events = Events.objects.filter(is_visible=True)
#     gallery = Gallery.objects.filter(is_visible=True)
#     context = {
#         'categories': categories,
#         'chefs': chefs,
#         'events': events,
#         'gallery': gallery,
#     }
#     return render(request, 'index.html', context=context)

home/templates/chefs.html
<!-- ======= Chefs Section ======= -->
    <section id="chefs" class="chefs section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Chefs</h2>
          <p>Our <span>Proffesional</span> Chefs</p>
        </div>

        <div class="row gy-4">
            {% for chef in chefs %}
          <div class="col-lg-4 col-md-6 d-flex align-items-stretch" data-aos="fade-up" data-aos-delay="100">
            <div class="chef-member">
              <div class="member-img">
                <img src="{{ chef.photo.url }}" class="img-fluid" alt="{{ chef.surname }}">
                <div class="social">
                  <a href=""><i class="bi bi-twitter"></i></a>
                  <a href=""><i class="bi bi-facebook"></i></a>
                  <a href=""><i class="bi bi-instagram"></i></a>
                  <a href=""><i class="bi bi-linkedin"></i></a>
                </div>
              </div>
              <div class="member-info">
                <h4>{{ chef }}</h4>
                <span>{{ chef.appointment }}</span>
                <p>{{ chef.description }}</p>
              </div>
            </div>
          </div><!-- End Chefs Member -->

            {% endfor %}
        </div>

      </div>
    </section><!-- End Chefs Section -->

home/templates/contacts.html
<!-- ======= Contact Section ======= -->
    <section id="contact" class="contact">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Contact</h2>
          <p>Need Help? <span>Contact Us</span></p>
        </div>



        <div class="row gy-4">

          <div class="col-md-6">
            <div class="info-item  d-flex align-items-center">
              <i class="icon bi bi-map flex-shrink-0"></i>
              <div>
                <h3>Our Address</h3>
                <p>{{ footer_items.address|safe }}</p>
              </div>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-6">
            <div class="info-item d-flex align-items-center">
              <i class="icon bi bi-envelope flex-shrink-0"></i>
              <div>
                <h3>Email Us</h3>
                <p>{{ footer_items.email }}</p>
              </div>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-6">
            <div class="info-item  d-flex align-items-center">
              <i class="icon bi bi-telephone flex-shrink-0"></i>
              <div>
                <h3>Call Us</h3>
                <p>{{ footer_items.email }}</p>
              </div>
            </div>
          </div><!-- End Info Item -->

          <div class="col-md-6">
            <div class="info-item  d-flex align-items-center">
              <i class="icon bi bi-share flex-shrink-0"></i>
              <div>
                <h3>Opening Hours</h3>
                <div><strong>Mon-Sat:</strong> {{ footer_items.working_hours|safe }}
                  <strong>Sunday:</strong> Closed
                </div>
              </div>
            </div>
          </div><!-- End Info Item -->

        </div>



      </div>
    </section><!-- End Contact Section -->

home/templates/events.html
<!-- ======= Events Section ======= -->
    <section id="events" class="events">
      <div class="container-fluid" data-aos="fade-up">

        <div class="section-header">
          <h2>Events</h2>
          <p>Share <span>Your Moments</span> In Our Restaurant</p>
        </div>

        <div class="slides-3 swiper" data-aos="fade-up" data-aos-delay="100">
          <div class="swiper-wrapper">

            {% for event in events %}
                <div class="swiper-slide event-item d-flex flex-column justify-content-end" style="background-image: url({{ event.photo.url }})">
                  <h3>{{ event.name }}</h3>
                  <div class="price align-self-start">${{ event.price }}</div>
                  <p class="description">{{ event.description }}</p>
                </div><!-- End Event item -->
            {% endfor %}

          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Events Section -->

home/templates/gallery.html
<!-- ======= Gallery Section ======= -->
    <section id="gallery" class="gallery section-bg">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>gallery</h2>
          <p>Check <span>Our Gallery</span></p>
        </div>

        <div class="gallery-slider swiper">
          <div class="swiper-wrapper align-items-center">
            {% for item in gallery %}
                <div class="swiper-slide">
                    <a class="glightbox" data-gallery="images-gallery" href="{{ item.photo.url }}">
                        <img src="{{ item.photo.url }}" class="img-fluid" alt="{{ item.name }}">
                    </a>
                </div>
            {% endfor %}
          </div>
          <div class="swiper-pagination"></div>
        </div>

      </div>
    </section><!-- End Gallery Section -->

home/templates/index.html
{% extends 'layouts/welcome.html' %}

{% block content %}
    {% include 'menu.html' %}
    {% include 'events.html' %}
    {% include 'chefs.html' %}
    {% include 'reservation.html' %}
    {% include 'gallery.html' %}
    {% include 'contacts.html' %}
{% endblock %}

home/templates/menu.html
<!-- ======= Menu Section ======= -->
<section id="menu" class="menu">
    <div class="container" data-aos="fade-up">
        <div class="section-header">
            <h2></h2>
            <p>Check Our <span>Yummy Menu</span></p>
        </div>

        <ul class="nav nav-tabs d-flex justify-content-center" data-aos="fade-up" data-aos-delay="200">
            {% for category in categories %}
                {% if forloop.first %}
                    <li class="nav-item">
                        <a class="nav-link active show" data-bs-toggle="tab" data-bs-target="#menu-{{ category.pk }}">
                          <h4>{{ category.name }}</h4>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" data-bs-toggle="tab" data-bs-target="#menu-{{ category.pk }}">
                          <h4>{{ category.name }}</h4>
                        </a>
                    </li>
                {% endif %}
            {% endfor %}
        </ul>

        <div class="tab-content" data-aos="fade-up" data-aos-delay="300">
            {% for category in categories %}
                {% if forloop.first %}
                    <div class="tab-pane fade active show" id="menu-{{ category.pk }}">
                        <div class="tab-header text-center">
                          <h3>{{ category.name }}</h3>
                        </div>
                        <div class="row gy-5">
                            {% for dish in category %}
                                <div class="col-lg-4 menu-item">
                                    <a href="{{ dish.photo.url }}" class="glightbox">
                                        <img src="{{ dish.photo.url }}" class="menu-img img-fluid" alt="">
                                    </a>
                                    <h4>{{ dish.name }}</h4>
                                    <p class="ingredients">
                                        {{ dish.ingredients }}
                                    </p>
                                    <p class="price">
                                        {{ dish.price }}
                                    </p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% else %}
                    <div class="tab-pane fade" id="menu-{{ category.pk }}">
                        <div class="tab-header text-center">
                          <h3>{{ category.name }}</h3>
                        </div>
                        <div class="row gy-5">
                            {% for dish in category %}
                                <div class="col-lg-4 menu-item">
                                    <a href="{{ dish.photo.url }}" class="glightbox">
                                        <img src="{{ dish.photo.url }}" class="menu-img img-fluid" alt="">
                                    </a>
                                    <h4>{{ dish.name }}</h4>
                                    <p class="ingredients">
                                        {{ dish.ingredients }}
                                    </p>
                                    <p class="price">
                                        {{ dish.price }}
                                    </p>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
        </div>

    </div>
</section>
<!-- End Menu Section -->

home/templates/reservation.html
<!-- ======= Book A Table Section ======= -->
    <section id="book-a-table" class="book-a-table">
      <div class="container" data-aos="fade-up">

        <div class="section-header">
          <h2>Book A Table</h2>
          <p>Book <span>Your Stay</span> With Us</p>
        </div>

        <div class="row g-0">

          <div class="col-lg-4 reservation-img" style="background-image: url(assets/img/reservation.jpg);" data-aos="zoom-out" data-aos-delay="200"></div>

          <div class="col-lg-8 d-flex align-items-center reservation-form-bg">
            <form action="{% url 'home:main_page' %}" method="post" role="form" class="php-email-form" data-aos="fade-up" data-aos-delay="100">
                {% csrf_token %}
{#                {{ reservation_form.as_p }}#}
              <div class="row gy-4">
                <div class="col-lg-4 col-md-6">
{#                  <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars">#}
                    {{ reservation_form.name }}
                  <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
{#                  <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email">#}
                    {{ reservation_form.email }}
                  <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
{#                  <input type="text" class="form-control" name="phone" id="phone" placeholder="Your Phone" data-rule="minlen:4" data-msg="Please enter at least 4 chars">#}
                    {{ reservation_form.phone }}
                    <div class="validate">{{ reservation_form.phone.errors }}</div>
                </div>
                <div class="col-lg-4 col-md-6">
{#                  <input type="text" name="date" class="form-control" id="date" placeholder="Date" data-rule="minlen:4" data-msg="Please enter at least 4 chars">#}
                    {{ reservation_form.date }}
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
{#                  <input type="text" class="form-control" name="time" id="time" placeholder="Time" data-rule="minlen:4" data-msg="Please enter at least 4 chars">#}
                    {{ reservation_form.time }}
                    <div class="validate"></div>
                </div>
                <div class="col-lg-4 col-md-6">
{#                  <input type="number" class="form-control" name="people" id="people" placeholder="# of people" data-rule="minlen:1" data-msg="Please enter at least 1 chars">#}
                    {{ reservation_form.number_people }}
                    <div class="validate"></div>
                </div>
              </div>
              <div class="form-group mt-3">
{#                <textarea class="form-control" name="message" rows="5" placeholder="Message"></textarea>#}
                  {{ reservation_form.message }}
                <div class="validate"></div>
              </div>
              <div class="mb-3">
                <div class="loading">Loading</div>
                <div class="error-message"></div>
                <div class="sent-message">Your booking request was sent. We will call back or send an Email to confirm your reservation. Thank you!</div>
              </div>
              <div class="text-center"><button type="submit">Book a Table</button></div>
            </form>
          </div><!-- End Reservation Form -->

        </div>

      </div>
    </section><!-- End Book A Table Section -->

templates/layouts/footer.html
<footer id="footer" class="footer">

    <div class="container">
      <div class="row gy-3">
        <div class="col-lg-3 col-md-6 d-flex">
          <i class="bi bi-geo-alt icon"></i>
          <div>
            <h4>Address</h4>
            <p>
              {{ footer_items.address|safe }}
            </p>
          </div>

        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-telephone icon"></i>
          <div>
            <h4>Reservations</h4>
            <p>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links d-flex">
          <i class="bi bi-clock icon"></i>
          <div>
            <h4>Opening Hours</h4>
            <p>
              <strong>Mon-Sat: 11AM</strong> - 23PM<br>
              Sunday: Closed
            </p>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 footer-links">
          <h4>Follow Us</h4>
          <div class="social-links d-flex">
            <a href="{{ footer_items.twitter }}" class="twitter"><i class="bi bi-twitter"></i></a>
            <a href="{{ footer_items.facebook }}" class="facebook"><i class="bi bi-facebook"></i></a>
            <a href="{{ footer_items.instagram }}" class="instagram"><i class="bi bi-instagram"></i></a>
            <a href="{{ footer_items.youtube }}" class="linkedin"><i class="bi bi-linkedin"></i></a>
          </div>
        </div>

      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>Yummy</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>

  </footer><!-- End Footer -->

templates/layouts/welcome.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Yummy Bootstrap Template - Index</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href={% static "assets/img/favicon.png" %} rel="icon">
  <link href={% static "assets/img/apple-touch-icon.png" %} rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Amatic+SC:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href={% static "assets/vendor/bootstrap/css/bootstrap.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/bootstrap-icons/bootstrap-icons.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/aos/aos.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/glightbox/css/glightbox.min.css" %} rel="stylesheet">
  <link href={% static "assets/vendor/swiper/swiper-bundle.min.css" %} rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href={% static "assets/css/main.css" %} rel="stylesheet">
</head>

<body>
  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <a href="{% url "home:main_page" %}" class="logo d-flex align-items-center me-auto me-lg-0">
        <h1>Yummy<span>.</span></h1>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a href="#menu">Menu</a></li>
          <li><a href="#events">Events</a></li>
          <li><a href="#chefs">Chefs</a></li>
          <li><a href="#gallery">Gallery</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-down dropdown-indicator"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav><!-- .navbar -->

      <a class="btn-book-a-table" href="#book-a-table">Book a Table</a>
      <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
      <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

    </div>
  </header><!-- End Header -->

  <main id="main">
      {% block content %}
      {% endblock %}

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  {% include 'layouts/footer.html' %}
  <!-- End Footer -->

  <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <div id="preloader"></div>

  <!-- Vendor JS Files -->
  <script src={% static "assets/vendor/bootstrap/js/bootstrap.bundle.min.js" %}></script>
  <script src={% static "assets/vendor/aos/aos.js" %}></script>
  <script src={% static "assets/vendor/glightbox/js/glightbox.min.js" %}></script>
  <script src={% static "assets/vendor/purecounter/purecounter_vanilla.js" %}></script>
  <script src={% static "assets/vendor/swiper/swiper-bundle.min.js" %}></script>


  <!-- Template Main JS File -->
  <script src={% static "assets/js/main.js" %}></script>

</body>

</html>